CREATE TABLE company_manager (
    `uid`    int(10)    NOT NULL,
    `id`    varchar(50)    NOT NULL,
    `password`    varchar(255)    NOT NULL,
    `name`    varchar(20)    NOT NULL,
    `email`    varchar(50)    NOT NULL,
    `mobile`    varchar(20)    NOT NULL,
    `zip_no`    int(10)    NULL,
    `address`    varchar(255)    NULL,
    `car_model`    varchar(80)    NOT NULL,
    `car_number`    varchar(50)    NOT NULL,
    `payment_card_company`    varchar(50)    NULL,
    `payment_card_number`    varchar(50)    NULL,
    `membership_card_number`    varchar(50)    NULL,
    `point`    int(255)    NOT NULL,
    `rfid`    varchar(100)    NULL,
    `registration`    varchar(100)    NULL,
    `certificate`    varchar(100)    NULL,
    `warrant`    varchar(100)    NULL,
    `copyid`    varchar(100)    NULL,
    `cal_name`    varchar(50)    NULL,
    `cal_email`    varchar(50)    NULL,
    `cal_mobile`    varchar(50)    NULL,
    `cal_tel`    varchar(50)    NULL,
    `cal_phone`    varchar(50)    NULL,
    `cal_fax`    varchar(50)    NULL,
    `reception_status`    int(4)   NULL,
    PRIMARY KEY(`uid`)
)ENGINE=InnoDB AUTO_INCREMENT=15 DEFAULT CHARSET=utf8mb4;
